package com.mycompany.app.seleniumide;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class LoginfalidoFirefoxTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(7, TimeUnit.SECONDS);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginfalido() {
    // Test name: Login falido
    // Step # | name | target | value
    // 1 | open | /wp-admin/ | 
    driver.get("https://cursosdedesarrollo.com/wp-admin/");
    // 2 | type | id=user_login | admin
    driver.findElement(By.id("user_login")).sendKeys("admin");
    // 3 | type | id=user_pass | asddads
    driver.findElement(By.id("user_pass")).sendKeys("asddads");
    // 4 | click | id=wp-submit | 
    driver.findElement(By.id("wp-submit")).click();
    // 5 | assertText | id=login_error | ERROR: The username or password you entered is incorrect. Lost your password?
    assertThat(driver.findElement(By.id("login_error")).getText(), containsString("ERROR:"));
  }
}
